//CREAR USUARIO

###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "David Calderon",
  "age": 21,
  "email": "calderon@gmail.com"
}

//TRAER TODOS LOS USUARIOS

###
GET http://localhost:9000/api/users HTTP/1.1

//TRAER UN USUARIO EN ESPECIFICO

###
GET http://localhost:9000/api/users/647288358dce631215a10aad HTTP/1.1

//ELIMINAR UN USUARIO

###
DELETE http://localhost:9000/api/users/6472a1b45730b9b7ad94dd96 HTTP/1.1


//ACTUALIZAR UN USUARIO

###
PUT http://localhost:9000/api/users/64728a693df33f77d7b09b18 HTTP/1.1
Content-Type: application/json

{
  "name": "Juan Sebastian",
  "age": 21,
  "email": "mahecha@gmail.com"
}
